- jrun
Adding `-B` to the maven arguments runs it in batch mode, which disables color output of commands.
When color output is enabled, [this line with sed](https://github.com/ctrueden/jrun/blob/3ddde431f6387d76088a12f1eb3fd8f49ff4091d/jrun#L365) does not work as intended, because the coloring information comes after the open bracket and before `INFO`, which causes problems with the symbolic linking.
> Add -B to mvnArgs to disable color output

- jrun/jrun.py
- do not expand each component separately
- repeat until no shortcut matches
Fixes #16
> Expand coordinate only from start of string

- jgo/jgo.py
Precedence (highest to lowest):
- `JGO_CACHE_DIR` environment variable
- `cacheDir` in `settings` sections in `~/.jgorc`
- `~/.jgo`
> Read cacheDir from environment variable JGO_CACHE_DIR

- jgo/jgo.py
This addresses multiple issues with Python jar linking:
- link type was ignored (#24)
- link type was not a command line argument (#25)
- no auto mode for link type (#22)
Fixes only partially #22 
Fixes #24 
Fixes #25 
@ctrueden do you have any objections against resolving #22 with a Python-only solution?
> Fix python jar linking

- jgo.sh
When using `jgo` from shell scripts I have found it desirable to detect the exit code of the launched Java application. This small change achieves that.
> Return exit code of launched Java application

- jgo/jgo.py
Example success code:
```
$ jgo -Xmx1g org.scijava:parsington 1+3; echo $?
4
0
```
Example failure code:
```
$ jgo -Xmx1y org.scijava:parsington 1+3; echo $?
Invalid maximum heap size: -Xmx1y
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
ERROR 2018-12-16 13:16:50,926: Error in `/usr/bin/java -cp /home/hanslovskyp/.jgo/org/scijava/parsington/RELEASE/* -Xmx1y org.scijava.parse.Main 1+3': 1
usage: jgo [-v] [-u] [-U] [-m] [--ignore-jgorc] [--link-type type] [--additional-jars jar [jar ...]] [--additional-endpoints endpoint [endpoint ...]] [JVM_OPTIONS [JVM_OPTIONS ...]] <endpoint> [main-args]
Run Java main class from maven coordinates.
optional arguments:
-h, --help            show this help message and exit
-v, --verbose …
```
> Return java exit code from python jgo

- .travis.yml
- .travis/build.sh
- jgo/jgo.py
- setup.py
- tests/test_parsington.py
Simple tests so far:
- test resolution for
- auto
- copy
- hard
- soft
- test parsington with argument `1+3`
Replaces #28
> Simple test backup

- jgo/jgo.py
Fixes #27
For comparison, run this script:
```sh
#/usr/bin/env sh
if [ -z "${CONDA_PREFIX}" ]; then
export PATH=$HOME/.local/bin:$PATH
fi
echo "Time with update"
time jgo -u org.janelia.saalfeldlab:paintera:0.8.2 --version 2>/dev/null
echo
echo
echo "Time without update"
time jgo org.janelia.saalfeldlab:paintera:0.8.2 --version 2>/dev/null
```
On latest conda-forge release:
```
Time with update
real    0m1.956s
user    0m5.883s
sys     0m0.240s
Time without update
real    0m1.912s
user    0m5.728s
sys     0m0.275s
```
On this PR branch:
```
Time with update
real    0m1.846s
user    0m5.401s
sys     0m0.270s
Time without update
real    0m0.369s
user    0m0.550s
sys     0m0.070s
```
> Do not update local jgo test unless -u or -U option specified

- jgo/__init__.py
- jgo/__main__.py
- jgo/util.py
1. Add `from .jgo import jgo_main as main`, so callers can use `import jgo; jgo.main(...)`.
2. Add utility/convenience methods, useful for distributing Java programs as python packages. E.g. for paintera, we only need:
```python
import jgo
jgo.main_from_endpoint(
'org.janelia.saalfeldlab:paintera',
primary_endpoint_version='0.8.1',
secondary_endpoints=('org.slf4j:slf4j-simple:1.7.25',),
)
```
Using a different main class from the same maven artifact:
```python
import jgo
import pathlib
jgo.main_from_endpoint(
argv=[str(pathlib.Path.home() / 'Downloads' / 'sample_A_padded_20160501.hdf'), '--revert-array-attributes'],
primary_endpoint='org.janelia.saalfeldlab:paintera',
primary_endpoint_version='0.8.1',
primary_endpoint_main_class='@PainteraShowContainer', …
```
> Better imports

- jgo/util.py
This was missed in the previous commit when changing from `maven.imagej.net` to `maven.scijava.org`.
> Rename imagej.public to scijava.public

- jgo/jgo.py
Using logging.basicConfig at this level of the program leads to this logging configuration being forced upon all programs that import jgo. Seeing how useful jgo is as a library, it should follow the python logging convention of libraries not hard-coding the logging configuration: https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library
----
Example code:
```
import logging
logging.basicConfig(filename='example.log', level=logging.DEBUG)
logger = logging.getLogger(__name__)
print(logger.name)
logger.debug('This message should go to the log file')
logger.info('So should this')
logger.warning('And this, too')
```
This code logs a few example messages to a log file. No library import should change how this code works. Adding `import jgo` at the beginning (or importing …
> Removing hard-coded logging configuration

- jgo/jgo.py
The try except for the `subprocess.check_output` seems to be required to be in the function that calls `subprocess.check_output`. If it's in a function that calls a function that calls `subprocess.check_output` (as it is so far), it does not catch the output and therefore does not work.
This pull request would take it into the `run_and_combine_outputs` function. In my tests, this then provides the actual error messages to the console (see [this forum thread ](https://forum.image.sc/t/using-pyinstaller-on-a-program-that-uses-pyimagej/26642/5)for details).
The only thing I haven't been able to here is integrate it with the parser for the `parser.print_help(file=sys.stderr)`. Could that be done from within `run_and_combine_outputs`? Can the parser be initialized multiple times or passed to …
> Move try except into run_and_combine_outputs function

- jgo/jgo.py
Also, remove commented out parser.<func> lines and unused variable `e`.
Use of `parser` was commented out in this function. One such line had remained uncommented and would throw an exception.
> Remove erroneous parser.print_help line

- jgo.sh
- jgo/jgo.py
Things to consider:
1. The actual message
2. currently, this message only shows with the `-v` flag in `jgo.sh`. Should we add another log level `warn` that does not check for `verbose`?
cc @ctrueden 
fixes #40
> Log first-time start up and warn about potentially slow start-up time

- README.md
- jgo/__init__.py
- jgo/__main__.py
- jgo/jgo.py
- jgo/util.py
- setup.py
- tests/test_parsington.py
- tox.ini
[`black`](https://github.com/psf/black) is a deterministic, opinionated python code formatter. It makes lots of good choices so we don't have to think about how our code looks anymore.
I added configuration using `tox` so anyone can easily run `black` in this repository if you just do:
```shell
$ pip install tox
$ tox -e lint
```
For all of the other open pull requests, they can also just use black directly to make it easier to merge their PRs by running black directly `black jgo/ tests/ setup.py`.
> Apply black to deterministally reformat all code

- jgo/jgo.py
To address https://github.com/scijava/jgo/issues/31#issuecomment-548056700
> Use sha256 hash of extra coordinates for cache dir name, pepify

- setup.py
- tests/test_managed.py
There were two python version requirements in `setup.py`, which leads to the following error.
```
~/miniconda3/envs/napari-imagej/bin/pip install -e .                                                                                                                                                                                                   # I 0 {2022-04-04 9:18:57}
Obtaining file:///home/gselzer/code/scijava/jgo
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [7 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/home/gselzer/code/scijava/jgo/setup.py", line 23
python_requires=">=3",
^ …
```
> Remove redundant python version

- .github/workflows/build.yml
- jgo/jgo.py
- jgo/util.py
- tests/test_parsington.py
- tests/test_run.py
- tox.ini
Relates to https://github.com/scijava/jgo/issues/44
This takes the coverage from 69% to slightly over 90%.
Many of the tests are using unrealistic arg combinations for various endpoints.  More than happy to adjust them to use more realistic scenarios.
> Add more tests

- jgo/jgo.py
When an argument passed to jgo starts with a windows drive letter (e.g. Z:\\), it detects this as a valid endpoint, and the endpoint index is much farther than it otherwise should be. This results in the last positional arg jgo attempts to parse to receive all the extra arguments, that should have otherwise been passed to the program jgo is launching. In my case, it was passing these extra args to the `-r` or `repository` flag, and failing since the windows paths were not valid maven repositories. 
There already was present a check to ignore args that match `Endpoint.is_endpoint` but contain `https://`, so I added an additional check to ignore an arg starting with a windows drive letter when considering the endpoint index.
> fix: don't include paths starting with Windows drive letters as endpoints

- src/jgo/util.py
- tests/test_run.py
When building tools based on jgo, `util.main_from_endpoint` is super useful to build up command line tools. Currently, however, it doesn't return the return code - so it is not possible for consumers to tell programmatically whether the jgo run was successful.
This PR makes sure to return the returncode.
> propagate return code in `util.main_from_endpoint`
